name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Install NetLogo
        run: |
          curl https://ccl.northwestern.edu/netlogo/6.1.1/NetLogo-6.1.1-64.tgz --output NetLogo-6.1.1-64.tgz
          tar xf NetLogo-6.1.1-64.tgz
          mv NetLogo\ 6.1.1 /opt/netlogo-6.1.1

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install nox
        run: pip install nox

      - name: Test
        run: |
          nox -s test --python ${{ matrix.python-version }}

      - name: Test BMI
        run: |
          nox -s test-bmi --python ${{ matrix.python-version }}

      - name: Run examples
        run: |
          nox -s run-examples --python ${{ matrix.python-version }}
